
name: Threeunits

on:
 push

jobs:
 build:
  runs-on: windows-latest
  steps:
   - uses: actions/checkout@v2
   - run: g++  *.cpp -o 
   - run: ./run_test.sh
   - run: diff native_output.txt units/out_ok.txt
